swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /info:
    get:
      operationId: Info
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /operation/{num1}/{num2}:
    get:
      operationId: Operation
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /payments:
    get:
      operationId: GetPayments
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /say:
    post:
      operationId: Say
      consumes:
      - '*/*'
      produces:
      - '*/*'
