swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /:
    get:
      operationId: Root
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /call:
    post:
      tags:
      - users
      - test
      operationId: Call
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /callphp:
    get:
      tags:
      - users
      - test
      operationId: CallPhp
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /getInfo:
    get:
      tags:
      - users
      - test
      operationId: GetUserInfo
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /metrics:
    get:
      operationId: HTTPHandleFunc
  /updateUser:
    post:
      tags:
      - users
      - test
      operationId: UpdateUserInfo
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
