swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /:
    get:
      operationId: Root
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /addrule:
    post:
      tags:
      - rule
      - name
      - programme
      - parameters
      operationId: AddRule
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /delrule:
    post:
      tags:
      - EntryID
      operationId: DelRule
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
  /getrulelist:
    post:
      tags:
      - rule
      - name
      - programme
      - parameters
      operationId: GetRuleList
      consumes:
      - '*/*'
      produces:
      - '*/*'
      responses:
        "200":
          description: ""
