swagger: "2.0"
info:
  title: ""
  version: ""
basePath: /
paths:
  /concurrency:
    get:
      operationId: MaxConcurrency
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /error:
    get:
      operationId: GetError
      consumes:
      - '*/*'
      produces:
      - '*/*'
  /lock:
    get:
      operationId: GetLock
      consumes:
      - '*/*'
      produces:
      - '*/*'
